<?php
$config=array();
$config["allow_comments"]="0";
$config["from_email"]="bionova@ukr.net";
$config["from_name"]=" ЮснаСуперБио";
$config["orders_email"]="bionova@ukr.net";
$config["spam_email"]="bionova@ukr.net";
$config["image_height"]="400";
$config["image_width"]="400";
$config["thumb_image_height"]="50";
$config["thumb_image_width"]="50";
$config["minimum_order_summ"]="150.00";
$config["number_of_products_on_page"]="50";
$config["delivery_variants"]="Самовывоз=0;Доставка курьером=0;Почтой или транспортной компанией=0";
$config["payments_variants"]="Наличными=0;Безналичный расчет=0;Наложенный платеж=0";
$config["items_per_tab"]="110";
$config["front_title"]="ЮснаСуперБио - ветпрепараты и товары для сельхоз животных, пчел, домашних животных, товары для аквариумистики";
$config["front_keywords"]="Интернет магазин зоотоваров ЮснаСуперБио, интернет-зоомагазин, интернет-зоомагазин, зоомагазины Киев, ветаптека, зоотовары, ветпрепараты, лекарства для пчел, товары для животных, всё для собак, всё для котов, всё для кошек, всё для птиц, всё для кроликов, всё для грызунов";
$config["front_description"]="ЮснаСуперБио - ветпрепараты и товары для сельхоз животных, пчел, домашних животных, товары для аквариумистики";
$config["ad_exp_header"]="ЮснаСуперБио - ветпрепараты и товары для сельхоз животных, пчел, домашних животных, товары для аквариумистики";
