<?php
$config=array();
$config["allow_comments"]="0";
$config["from_email"]="bionova@ukr.net";
$config["from_name"]="Ардена";
$config["orders_email"]="bionova@ukr.net";
$config["spam_email"]="bionova@ukr.net";
$config["image_height"]="400";
$config["image_width"]="400";
$config["thumb_image_height"]="50";
$config["thumb_image_width"]="50";
$config["minimum_order_summ"]="150.00";
$config["number_of_products_on_page"]="50";
$config["delivery_variants"]="Самовывоз=0;Доставка курьером=0;Почтой или транспортной компанией=0";
$config["payments_variants"]="Наличными=0;Безналичный расчет=0;Наложенный платеж=0";
$config["items_per_tab"]="64";
$config["front_title"]="Ардена - товары для дома, дачи и огорода";
$config["front_keywords"]="Ардена - товары для дома, дачи и огорода";
$config["front_description"]="Ардена - товары для дома, дачи и огорода";
$config["ad_exp_header"]="Ардена - магазин для агрономов и для тех кто любит растения";
