// RU lang variables Translate 07.04.2008 by Greycat. joomlaforum.ru

tinyMCE.addToLang('advlink',{
general_tab : 'Общее',
popup_tab : 'Всплывающее окно',
events_tab : 'События',
advanced_tab : 'Подробнее',
general_props : 'Общие параметры',
popup_props : 'Параметры всплывающих окон',
event_props : 'События',
advanced_props : 'Расширенные параметры',
popup_opts : 'Настройки',
anchor_names : 'Якоря',
target_same : 'Открывать в этом окне/фрейме',
target_parent : 'Открывать в родительском окне/фрейме',
target_top : 'Открывать в верхнем (top) фрейме (заменять все фреймы)',
target_blank : 'Открывать в новом окне',
popup : 'Всплывающее окно Javascript',
popup_url : 'Ссылка для всплывающего окна',
popup_name : 'Заголовок окна',
popup_return : 'Вставить \'return false\'',
popup_scrollbars : 'Показывать линейки прокрутки',
popup_statusbar : 'Показывать строку статуса',
popup_toolbar : 'Показывать панели инструментов',
popup_menubar : 'Показывать меню',
popup_location : 'Показывать строку адреса',
popup_resizable : 'Разрешить изменять размеры',
popup_dependent : 'Зависимый (для Mozilla/Firefox)',
popup_size : 'Размер',
popup_position : 'Позиция (X/Y)',
id : 'Id',
style: 'Стиль',
classes : 'Классы',
target_name : 'Имя для назначения',
langdir : 'Направление текста',
target_langcode : 'Язык назначения',
langcode : 'Код языка',
encoding : 'Кодировка назначения',
mime : 'MIME-тип назначения',
rel : 'Зависимость страницы от назначения',
rev : 'Зависимость назначения от страницы',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Слева направо',
rtl : 'Справа налево'
});