<?php
$config=array();
$config["allow_comments"]="0";
$config["from_email"]="bionova@ukr.net";
$config["from_name"]="Аквариумистика";
$config["orders_email"]="bionova@ukr.net";
$config["spam_email"]="bionova@ukr.net";
$config["image_height"]="400";
$config["image_width"]="400";
$config["thumb_image_height"]="50";
$config["thumb_image_width"]="50";
$config["minimum_order_summ"]="150.00";
$config["number_of_products_on_page"]="50";
$config["delivery_variants"]="Самовывоз=0;Доставка курьером=0;Почтой или транспортной компанией=0";
$config["payments_variants"]="Наличными=0;Безналичный расчет=0;Наложенный платеж=0";
$config["items_per_tab"]="64";
$config["front_title"]="Аквариумистика Нова, магазин аквариумистики, куплю аквариум, аквариумные рыбки, названия аквариумных рыбок, купить фильтр для аквариума, лампы для акварума, освещение аквариума, крышка для аквариума, растения для аквариума, ";
$config["front_keywords"]="Аквариумистика Нова, уход за аквариумом, помпа для аквариума, сколько стоит аквариум, красивые аквариумы, как менять воду в аквариуме, почему мутнеет аквариум, виды аквариумных рыбок, ";
$config["front_description"]="Аквариумистика Нова, корм для рыбок, обогрев аквариума, витамины для аквариумных рыб, аэратор для аквариума, альгициды аквариума, ";
$config["ad_exp_header"]="Аквариумистика Нова- центр современной аквариумистик и и аквадизайна";
